name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-gnu

      - name: Build binaries
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu

      - name: Create archives
        run: |
          tar -czf reviewr-x86_64-unknown-linux-gnu.tar.gz -C target/x86_64-unknown-linux-gnu/release reviewr

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            reviewr-x86_64-unknown-linux-gnu.tar.gz

      - name: Check Homebrew tap access
        id: check-tap
        run: |
          if [ -n "${{ secrets.HOMEBREW_TAP_TOKEN }}" ]; then
            if curl -s -H "Authorization: token ${{ secrets.HOMEBREW_TAP_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/kain88-de/homebrew-reviewr > /dev/null 2>&1; then
              echo "tap-accessible=true" >> $GITHUB_OUTPUT
            else
              echo "tap-accessible=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "tap-accessible=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Homebrew tap
        if: steps.check-tap.outputs.tap-accessible == 'true'
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: reviewr
          formula-path: Formula/reviewr.rb
          homebrew-tap: kain88-de/homebrew-reviewr
          download-url: https://github.com/kain88-de/reviewr/releases/download/${{ github.ref_name }}/reviewr-x86_64-unknown-linux-gnu.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
