name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-gnu

      - name: Build binaries
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu

      - name: Create archives
        run: |
          tar -czf eval-x86_64-unknown-linux-gnu.tar.gz -C target/x86_64-unknown-linux-gnu/release eval

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eval-x86_64-unknown-linux-gnu.tar.gz

      - name: Update Homebrew tap
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          tap: kain88-de/eval
          formula: eval
