name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-gnu

      - name: Build binaries
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu

      - name: Create archives
        run: |
          tar -czf reviewr-x86_64-unknown-linux-gnu.tar.gz -C target/x86_64-unknown-linux-gnu/release reviewr

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            reviewr-x86_64-unknown-linux-gnu.tar.gz

      - name: Update Homebrew tap
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: eval
          formula-path: Formula/eval.rb
          homebrew-tap: kain88-de/homebrew-eval
          download-url: https://github.com/kain88-de/eval/releases/download/${{ github.ref_name }}/reviewr-x86_64-unknown-linux-gnu.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
